/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.2.0.0 (NJsonSchema v10.1.2.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const HURACE_SERVICE_BASE_URL = new InjectionToken<string>('HURACE_SERVICE_BASE_URL');

@Injectable()
export class ApiService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(HURACE_SERVICE_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    returns_all_countries(): Observable<Country[]> {
        let url_ = this.baseUrl + "/api/Country";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_countries(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_countries(<any>response_);
                } catch (e) {
                    return <Observable<Country[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Country[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_countries(response: HttpResponseBase): Observable<Country[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Country[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_country_for_a_passed_country_Id(countryId: number): Observable<Country> {
        let url_ = this.baseUrl + "/api/Country/{countryId}";
        if (countryId === undefined || countryId === null)
            throw new Error("The parameter 'countryId' must be defined.");
        url_ = url_.replace("{countryId}", encodeURIComponent("" + countryId)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_country_for_a_passed_country_Id(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_country_for_a_passed_country_Id(<any>response_);
                } catch (e) {
                    return <Observable<Country>><any>_observableThrow(e);
                }
            } else
                return <Observable<Country>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_country_for_a_passed_country_Id(response: HttpResponseBase): Observable<Country> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Country>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            result404 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_all_races(): Observable<Race[]> {
        let url_ = this.baseUrl + "/api/Race";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_races(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_races(<any>response_);
                } catch (e) {
                    return <Observable<Race[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Race[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_races(response: HttpResponseBase): Observable<Race[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Race[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    race_GetRacesByFilter(raceFilter: RaceFilter): Observable<Race[]> {
        let url_ = this.baseUrl + "/api/Race";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(raceFilter);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRace_GetRacesByFilter(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRace_GetRacesByFilter(<any>response_);
                } catch (e) {
                    return <Observable<Race[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Race[]>><any>_observableThrow(response_);
        }));
    }

    protected processRace_GetRacesByFilter(response: HttpResponseBase): Observable<Race[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Race[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Race[]>(<any>null);
    }

    returns_race_for_the_given_raceId(raceId: number): Observable<Race> {
        let url_ = this.baseUrl + "/api/Race/{raceId}";
        if (raceId === undefined || raceId === null)
            throw new Error("The parameter 'raceId' must be defined.");
        url_ = url_.replace("{raceId}", encodeURIComponent("" + raceId)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_race_for_the_given_raceId(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_race_for_the_given_raceId(<any>response_);
                } catch (e) {
                    return <Observable<Race>><any>_observableThrow(e);
                }
            } else
                return <Observable<Race>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_race_for_the_given_raceId(response: HttpResponseBase): Observable<Race> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Race>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            result404 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_ranked_skiers_of_specific_race(raceId: number): Observable<RankedSkier[]> {
        let url_ = this.baseUrl + "/api/Race/{raceId}/ranks";
        if (raceId === undefined || raceId === null)
            throw new Error("The parameter 'raceId' must be defined.");
        url_ = url_.replace("{raceId}", encodeURIComponent("" + raceId)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_ranked_skiers_of_specific_race(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_ranked_skiers_of_specific_race(<any>response_);
                } catch (e) {
                    return <Observable<RankedSkier[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<RankedSkier[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_ranked_skiers_of_specific_race(response: HttpResponseBase): Observable<RankedSkier[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <RankedSkier[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            result404 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_all_race_states(): Observable<RaceState[]> {
        let url_ = this.baseUrl + "/api/RaceState";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_race_states(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_race_states(<any>response_);
                } catch (e) {
                    return <Observable<RaceState[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<RaceState[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_race_states(response: HttpResponseBase): Observable<RaceState[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <RaceState[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_all_race_types(): Observable<RaceType[]> {
        let url_ = this.baseUrl + "/api/RaceType";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_race_types(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_race_types(<any>response_);
                } catch (e) {
                    return <Observable<RaceType[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<RaceType[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_race_types(response: HttpResponseBase): Observable<RaceType[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <RaceType[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_all_seasons(): Observable<Season[]> {
        let url_ = this.baseUrl + "/api/Season";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_seasons(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_seasons(<any>response_);
                } catch (e) {
                    return <Observable<Season[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Season[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_seasons(response: HttpResponseBase): Observable<Season[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Season[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_all_skiers(): Observable<Skier[]> {
        let url_ = this.baseUrl + "/api/Skier";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_skiers(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_skiers(<any>response_);
                } catch (e) {
                    return <Observable<Skier[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Skier[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_skiers(response: HttpResponseBase): Observable<Skier[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Skier[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    returns_all_venues(): Observable<Venue[]> {
        let url_ = this.baseUrl + "/api/Venue";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_all_venues(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_all_venues(<any>response_);
                } catch (e) {
                    return <Observable<Venue[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Venue[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_all_venues(response: HttpResponseBase): Observable<Venue[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Venue[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }
}

export interface DomainObjectBase {
    id?: number;
}

export interface Country extends DomainObjectBase {
    name?: string | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    extensions?: { [key: string]: any; } | undefined;
}

export interface Race extends DomainObjectBase {
    date?: Date;
    description?: string | undefined;
    numberOfSensors?: number;
    overallRaceState?: AssociatedOfRaceState | undefined;
    raceType?: AssociatedOfRaceType | undefined;
    venue?: AssociatedOfVenue | undefined;
    season?: AssociatedOfSeason | undefined;
    firstStartList?: AssociatedOfStartPosition[] | undefined;
    secondStartList?: AssociatedOfStartPosition[] | undefined;
    skiers?: AssociatedOfSkier[] | undefined;
    genderSpecificRaceId?: number;
}

export interface AssociatedOfRaceState {
    foreignKey?: number | undefined;
    reference?: RaceState | undefined;
    initialised?: boolean;
}

export interface RaceState extends DomainObjectBase {
    label?: string | undefined;
}

export interface AssociatedOfRaceType {
    foreignKey?: number | undefined;
    reference?: RaceType | undefined;
    initialised?: boolean;
}

export interface RaceType extends DomainObjectBase {
    label?: string | undefined;
}

export interface AssociatedOfVenue {
    foreignKey?: number | undefined;
    reference?: Venue | undefined;
    initialised?: boolean;
}

export interface Venue extends DomainObjectBase {
    name?: string | undefined;
    country?: AssociatedOfCountry | undefined;
    seasons?: AssociatedOfSeason[] | undefined;
}

export interface AssociatedOfCountry {
    foreignKey?: number | undefined;
    reference?: Country | undefined;
    initialised?: boolean;
}

export interface AssociatedOfSeason {
    foreignKey?: number | undefined;
    reference?: Season | undefined;
    initialised?: boolean;
}

export interface Season extends DomainObjectBase {
    name?: string | undefined;
    startDate?: Date;
    endDate?: Date;
}

export interface AssociatedOfStartPosition {
    foreignKey?: number | undefined;
    reference?: StartPosition | undefined;
    initialised?: boolean;
}

export interface StartPosition extends DomainObjectBase {
    position?: number;
    skier?: AssociatedOfSkier | undefined;
}

export interface AssociatedOfSkier {
    foreignKey?: number | undefined;
    reference?: Skier | undefined;
    initialised?: boolean;
}

export interface Skier extends DomainObjectBase {
    firstName?: string | undefined;
    lastName?: string | undefined;
    dateOfBirth?: Date;
    imageUrl?: string | undefined;
    isRemoved?: boolean;
    startPositions?: AssociatedOfStartPosition[] | undefined;
    country?: AssociatedOfCountry | undefined;
    sex?: AssociatedOfSex | undefined;
}

export interface AssociatedOfSex {
    foreignKey?: number | undefined;
    reference?: Sex | undefined;
    initialised?: boolean;
}

export interface Sex extends DomainObjectBase {
    label?: string | undefined;
}

export interface RankedSkier extends Skier {
    rank?: number;
    elapsedTimeInFirstRun?: string;
    elapsedTimeInFirstRunString?: string | undefined;
    elapsedTimeInSecondRun?: string;
    elapsedTimeInSecondRunString?: string | undefined;
    elapsedTotalTime?: string;
    elapsedTotalTimeString?: string | undefined;
}

export interface RaceFilter {
    raceTypeIds?: number[] | undefined;
    seasonIds?: number[] | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}