/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.6.0 (NJsonSchema v10.0.28.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const HURACE_SERVICE_BASE_URL = new InjectionToken<string>('HURACE_SERVICE_BASE_URL');

@Injectable()
export class ConverterClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(HURACE_SERVICE_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getAllRaces(): Observable<Race[]> {
        let url_ = this.baseUrl + "/api/Race";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAllRaces(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllRaces(<any>response_);
                } catch (e) {
                    return <Observable<Race[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Race[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetAllRaces(response: HttpResponseBase): Observable<Race[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Race[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Race[]>(<any>null);
    }
}

export interface DomainObjectBase {
    id?: number;
}

export interface Race extends DomainObjectBase {
    date?: Date;
    description?: string | undefined;
    numberOfSensors?: number;
    overallRaceState?: AssociatedOfRaceState | undefined;
    raceType?: AssociatedOfRaceType | undefined;
    venue?: AssociatedOfVenue | undefined;
    season?: AssociatedOfSeason | undefined;
    firstStartList?: AssociatedOfStartPosition[] | undefined;
    secondStartList?: AssociatedOfStartPosition[] | undefined;
    skiers?: AssociatedOfSkier[] | undefined;
    genderSpecificRaceId?: number;
}

export interface AssociatedOfRaceState {
    foreignKey?: number | undefined;
    reference?: RaceState | undefined;
    initialised?: boolean;
}

export interface RaceState extends DomainObjectBase {
    label?: string | undefined;
}

export interface AssociatedOfRaceType {
    foreignKey?: number | undefined;
    reference?: RaceType | undefined;
    initialised?: boolean;
}

export interface RaceType extends DomainObjectBase {
    label?: string | undefined;
}

export interface AssociatedOfVenue {
    foreignKey?: number | undefined;
    reference?: Venue | undefined;
    initialised?: boolean;
}

export interface Venue extends DomainObjectBase {
    name?: string | undefined;
    country?: AssociatedOfCountry | undefined;
    seasons?: AssociatedOfSeason[] | undefined;
}

export interface AssociatedOfCountry {
    foreignKey?: number | undefined;
    reference?: Country | undefined;
    initialised?: boolean;
}

export interface Country extends DomainObjectBase {
    name?: string | undefined;
}

export interface AssociatedOfSeason {
    foreignKey?: number | undefined;
    reference?: Season | undefined;
    initialised?: boolean;
}

export interface Season extends DomainObjectBase {
    name?: string | undefined;
    startDate?: Date;
    endDate?: Date;
}

export interface AssociatedOfStartPosition {
    foreignKey?: number | undefined;
    reference?: StartPosition | undefined;
    initialised?: boolean;
}

export interface StartPosition extends DomainObjectBase {
    position?: number;
    skier?: AssociatedOfSkier | undefined;
}

export interface AssociatedOfSkier {
    foreignKey?: number | undefined;
    reference?: Skier | undefined;
    initialised?: boolean;
}

export interface Skier extends DomainObjectBase {
    firstName?: string | undefined;
    lastName?: string | undefined;
    dateOfBirth?: Date;
    imageUrl?: string | undefined;
    isRemoved?: boolean;
    startPositions?: AssociatedOfStartPosition[] | undefined;
    country?: AssociatedOfCountry | undefined;
    sex?: AssociatedOfSex | undefined;
}

export interface AssociatedOfSex {
    foreignKey?: number | undefined;
    reference?: Sex | undefined;
    initialised?: boolean;
}

export interface Sex extends DomainObjectBase {
    label?: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}