/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.6.0 (NJsonSchema v10.0.28.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const HURACE_SERVICE_BASE_URL = new InjectionToken<string>('HURACE_SERVICE_BASE_URL');

@Injectable()
export class ConverterClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(HURACE_SERVICE_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    country_GetAllCountries(): Observable<Country[]> {
        let url_ = this.baseUrl + "/api/Country";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCountry_GetAllCountries(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCountry_GetAllCountries(<any>response_);
                } catch (e) {
                    return <Observable<Country[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Country[]>><any>_observableThrow(response_);
        }));
    }

    protected processCountry_GetAllCountries(response: HttpResponseBase): Observable<Country[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Country[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Country[]>(<any>null);
    }

    returns_Country_for_the_country_Id(countryId: number): Observable<Country> {
        let url_ = this.baseUrl + "/api/Country/{countryId}";
        if (countryId === undefined || countryId === null)
            throw new Error("The parameter 'countryId' must be defined.");
        url_ = url_.replace("{countryId}", encodeURIComponent("" + countryId)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_Country_for_the_country_Id(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_Country_for_the_country_Id(<any>response_);
                } catch (e) {
                    return <Observable<Country>><any>_observableThrow(e);
                }
            } else
                return <Observable<Country>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_Country_for_the_country_Id(response: HttpResponseBase): Observable<Country> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Country>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            result404 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    race_GetAllRaces(): Observable<Race[]> {
        let url_ = this.baseUrl + "/api/Race";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRace_GetAllRaces(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRace_GetAllRaces(<any>response_);
                } catch (e) {
                    return <Observable<Race[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Race[]>><any>_observableThrow(response_);
        }));
    }

    protected processRace_GetAllRaces(response: HttpResponseBase): Observable<Race[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Race[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Race[]>(<any>null);
    }

    returns_race_for_the_given_raceId(raceId: number): Observable<Race> {
        let url_ = this.baseUrl + "/api/Race/{raceId}";
        if (raceId === undefined || raceId === null)
            throw new Error("The parameter 'raceId' must be defined.");
        url_ = url_.replace("{raceId}", encodeURIComponent("" + raceId)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_race_for_the_given_raceId(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_race_for_the_given_raceId(<any>response_);
                } catch (e) {
                    return <Observable<Race>><any>_observableThrow(e);
                }
            } else
                return <Observable<Race>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_race_for_the_given_raceId(response: HttpResponseBase): Observable<Race> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Race>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            result404 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    raceState_GetAllRaceStates(): Observable<RaceState[]> {
        let url_ = this.baseUrl + "/api/RaceState";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRaceState_GetAllRaceStates(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRaceState_GetAllRaceStates(<any>response_);
                } catch (e) {
                    return <Observable<RaceState[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<RaceState[]>><any>_observableThrow(response_);
        }));
    }

    protected processRaceState_GetAllRaceStates(response: HttpResponseBase): Observable<RaceState[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <RaceState[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<RaceState[]>(<any>null);
    }

    raceType_GetAllRaceTypes(): Observable<RaceType[]> {
        let url_ = this.baseUrl + "/api/RaceType";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRaceType_GetAllRaceTypes(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRaceType_GetAllRaceTypes(<any>response_);
                } catch (e) {
                    return <Observable<RaceType[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<RaceType[]>><any>_observableThrow(response_);
        }));
    }

    protected processRaceType_GetAllRaceTypes(response: HttpResponseBase): Observable<RaceType[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <RaceType[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<RaceType[]>(<any>null);
    }

    season_GetAllRaces(): Observable<Season[]> {
        let url_ = this.baseUrl + "/api/Season";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSeason_GetAllRaces(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSeason_GetAllRaces(<any>response_);
                } catch (e) {
                    return <Observable<Season[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Season[]>><any>_observableThrow(response_);
        }));
    }

    protected processSeason_GetAllRaces(response: HttpResponseBase): Observable<Season[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Season[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Season[]>(<any>null);
    }

    skier_GetAllRaces(): Observable<Skier[]> {
        let url_ = this.baseUrl + "/api/Skier";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSkier_GetAllRaces(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSkier_GetAllRaces(<any>response_);
                } catch (e) {
                    return <Observable<Skier[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Skier[]>><any>_observableThrow(response_);
        }));
    }

    protected processSkier_GetAllRaces(response: HttpResponseBase): Observable<Skier[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Skier[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Skier[]>(<any>null);
    }

    returns_skiers_for_the_given_raceId(raceId: number): Observable<Skier[]> {
        let url_ = this.baseUrl + "/api/Skier/{raceId}";
        if (raceId === undefined || raceId === null)
            throw new Error("The parameter 'raceId' must be defined.");
        url_ = url_.replace("{raceId}", encodeURIComponent("" + raceId)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReturns_skiers_for_the_given_raceId(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReturns_skiers_for_the_given_raceId(<any>response_);
                } catch (e) {
                    return <Observable<Skier[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Skier[]>><any>_observableThrow(response_);
        }));
    }

    protected processReturns_skiers_for_the_given_raceId(response: HttpResponseBase): Observable<Skier[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Skier[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            result404 = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let resultdefault: any = null;
            resultdefault = _responseText === "" ? null : <ProblemDetails>JSON.parse(_responseText, this.jsonParseReviver);
            return throwException("A server side error occurred.", status, _responseText, _headers, resultdefault);
            }));
        }
    }

    venue_GetAllRaces(): Observable<Venue[]> {
        let url_ = this.baseUrl + "/api/Venue";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processVenue_GetAllRaces(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processVenue_GetAllRaces(<any>response_);
                } catch (e) {
                    return <Observable<Venue[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<Venue[]>><any>_observableThrow(response_);
        }));
    }

    protected processVenue_GetAllRaces(response: HttpResponseBase): Observable<Venue[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Venue[]>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Venue[]>(<any>null);
    }
}

export interface DomainObjectBase {
    id?: number;
}

export interface Country extends DomainObjectBase {
    name?: string | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    extensions?: { [key: string]: any; } | undefined;
}

export interface Race extends DomainObjectBase {
    date?: Date;
    description?: string | undefined;
    numberOfSensors?: number;
    overallRaceState?: AssociatedOfRaceState | undefined;
    raceType?: AssociatedOfRaceType | undefined;
    venue?: AssociatedOfVenue | undefined;
    season?: AssociatedOfSeason | undefined;
    firstStartList?: AssociatedOfStartPosition[] | undefined;
    secondStartList?: AssociatedOfStartPosition[] | undefined;
    skiers?: AssociatedOfSkier[] | undefined;
    genderSpecificRaceId?: number;
}

export interface AssociatedOfRaceState {
    foreignKey?: number | undefined;
    reference?: RaceState | undefined;
    initialised?: boolean;
}

export interface RaceState extends DomainObjectBase {
    label?: string | undefined;
}

export interface AssociatedOfRaceType {
    foreignKey?: number | undefined;
    reference?: RaceType | undefined;
    initialised?: boolean;
}

export interface RaceType extends DomainObjectBase {
    label?: string | undefined;
}

export interface AssociatedOfVenue {
    foreignKey?: number | undefined;
    reference?: Venue | undefined;
    initialised?: boolean;
}

export interface Venue extends DomainObjectBase {
    name?: string | undefined;
    country?: AssociatedOfCountry | undefined;
    seasons?: AssociatedOfSeason[] | undefined;
}

export interface AssociatedOfCountry {
    foreignKey?: number | undefined;
    reference?: Country | undefined;
    initialised?: boolean;
}

export interface AssociatedOfSeason {
    foreignKey?: number | undefined;
    reference?: Season | undefined;
    initialised?: boolean;
}

export interface Season extends DomainObjectBase {
    name?: string | undefined;
    startDate?: Date;
    endDate?: Date;
}

export interface AssociatedOfStartPosition {
    foreignKey?: number | undefined;
    reference?: StartPosition | undefined;
    initialised?: boolean;
}

export interface StartPosition extends DomainObjectBase {
    position?: number;
    skier?: AssociatedOfSkier | undefined;
}

export interface AssociatedOfSkier {
    foreignKey?: number | undefined;
    reference?: Skier | undefined;
    initialised?: boolean;
}

export interface Skier extends DomainObjectBase {
    firstName?: string | undefined;
    lastName?: string | undefined;
    dateOfBirth?: Date;
    imageUrl?: string | undefined;
    isRemoved?: boolean;
    startPositions?: AssociatedOfStartPosition[] | undefined;
    country?: AssociatedOfCountry | undefined;
    sex?: AssociatedOfSex | undefined;
}

export interface AssociatedOfSex {
    foreignKey?: number | undefined;
    reference?: Sex | undefined;
    initialised?: boolean;
}

export interface Sex extends DomainObjectBase {
    label?: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}